#================================================================================
#  Configure and add AXI slaves
#  Auto-generated by 
#================================================================================
#SM_INFO
[AXI_PL_DEV_CONNECT SM_INFO   ${AXI_INTERCONNECT_NAME} ${AXI_MASTER_CLK} ${AXI_MASTER_RSTN} ${AXI_MASTER_CLK_FREQ} 0xA000C000 8K]

