set name iBert

set output_path ${apollo_root_path}/configs/${build_name}/cores/

file mkdir ${output_path}

file delete -force ${apollo_root_path}/configs/${build_name}/cores/${name}

#create IP
create_ip -vlnv [get_ipdefs -filter {NAME == ibert_7series_gtx}] -module_name ${name} -dir ${output_path}



set_property -dict [list \
			CONFIG.C_PROTOCOL_QUAD0 {None} \
			CONFIG.C_PROTOCOL_QUAD1 {None} \
			CONFIG.C_PROTOCOL_QUAD2 {Custom_1_/_5_Gbps} \
			CONFIG.C_PROTOCOL_QUAD3 {Custom_1_/_5_Gbps} \
			CONFIG.C_PROTOCOL_QUAD4 {None} \
			CONFIG.C_PROTOCOL_QUAD5 {None} \
			CONFIG.C_PROTOCOL_QUAD6 {None} \
			CONFIG.C_PROTOCOL_QUAD7 {None} \
			CONFIG.C_PROTOCOL_QUAD8 {None} \
			CONFIG.C_PROTOCOL_QUAD9 {None} \
			CONFIG.C_PROTOCOL_QUAD10 {None} \
			CONFIG.C_PROTOCOL_QUAD11 {None} \
			CONFIG.C_PROTOCOL_QUAD12 {None} \
			CONFIG.C_PROTOCOL_QUAD13 {None} \
			CONFIG.C_PROTOCOL_QUAD14 {None} \
			CONFIG.C_PROTOCOL_QUAD15 {None} \
			CONFIG.C_REFCLK_SOURCE_QUAD_0 {None} \
			CONFIG.C_REFCLK_SOURCE_QUAD_1 {None} \
			CONFIG.C_REFCLK_SOURCE_QUAD_2 {MGTREFCLK0_112} \
			CONFIG.C_REFCLK_SOURCE_QUAD_3 {MGTREFCLK0_112} \
			CONFIG.C_REFCLK_SOURCE_QUAD_4 {None} \
			CONFIG.C_REFCLK_SOURCE_QUAD_5 {None} \
			CONFIG.C_REFCLK_SOURCE_QUAD_6 {None} \
			CONFIG.C_REFCLK_SOURCE_QUAD_7 {None} \
			CONFIG.C_REFCLK_SOURCE_QUAD_8 {None} \
			CONFIG.C_REFCLK_SOURCE_QUAD_9 {None} \
			CONFIG.C_REFCLK_SOURCE_QUAD_10 {None} \
			CONFIG.C_REFCLK_SOURCE_QUAD_11 {None} \
			CONFIG.C_REFCLK_SOURCE_QUAD_12 {None} \
			CONFIG.C_REFCLK_SOURCE_QUAD_13 {None} \
			CONFIG.C_REFCLK_SOURCE_QUAD_14 {None} \
			CONFIG.C_REFCLK_SOURCE_QUAD_15 {None} \
			CONFIG.C_CHANNEL_QUAD_0 {Channel_0} \
			CONFIG.C_CHANNEL_QUAD_1 {Channel_0} \
			CONFIG.C_CHANNEL_QUAD_2 {Channel_0} \
			CONFIG.C_CHANNEL_QUAD_3 {Channel_0} \
			CONFIG.C_CHANNEL_QUAD_4 {Channel_0} \
			CONFIG.C_CHANNEL_QUAD_5 {Channel_0} \
			CONFIG.C_CHANNEL_QUAD_6 {Channel_0} \
			CONFIG.C_CHANNEL_QUAD_7 {Channel_0} \
			CONFIG.C_CHANNEL_QUAD_8 {Channel_0} \
			CONFIG.C_CHANNEL_QUAD_9 {Channel_0} \
			CONFIG.C_CHANNEL_QUAD_10 {Channel_0} \
			CONFIG.C_CHANNEL_QUAD_11 {Channel_0} \
			CONFIG.C_CHANNEL_QUAD_12 {Channel_0} \
			CONFIG.C_CHANNEL_QUAD_13 {Channel_0} \
			CONFIG.C_CHANNEL_QUAD_14 {Channel_0} \
			CONFIG.C_CHANNEL_QUAD_15 {Channel_0} \
			CONFIG.C_PROTOCOL_MAXLINERATE_1 {5} \
			CONFIG.C_PROTOCOL_RXREFCLK_FREQUENCY_1 {100.000} \
			CONFIG.C_PROTOCOL_GT_COUNT_1 {2} \
			CONFIG.C_SYSCLOCK_SOURCE_INT {QUAD112_0} \
			CONFIG.C_RXOUTCLK_GT_LOCATION {QUAD_112} \
			CONFIG.C_RXOUTCLK_PIN_STD {DIFF_SSTL15} \
			CONFIG.C_RXOUTCLK_FREQUENCY {156.25} \
			CONFIG.C_SYSCLK_MODE_EXTERNAL {0} \
			CONFIG.C_SYSCLK_IO_PIN_STD {DIFF_SSTL15} \
			CONFIG.C_SYSCLK_FREQUENCY {100.000} \
			CONFIG.C_SYSCLK_IO_PIN_LOC_N {UNASSIGNED} \
			CONFIG.C_SYSCLK_IO_PIN_LOC_P {UNASSIGNED} \
			\
			CONFIG.C_PROTOCOL_QUAD2 {Custom_1_/_5_Gbps} \
			CONFIG.C_PROTOCOL_QUAD3 {Custom_1_/_5_Gbps} \
			CONFIG.C_PROTOCOL_GT_COUNT_2 {0} \
			CONFIG.C_PROTOCOL_GT_COUNT_3 {0} \
		       ] [get_ips ${name}]
