#!/bin/sh

echo "Zynq Bootscript"

#if the key doesn't exist already, create it in /tmp and move it to /fw
if [ ! -f "/fw/dropbear_rsa_host_key" ]; then dropbearkey -t rsa -f /tmp/dropbear_rsa_host_key; mv /tmp/dropbear_rsa_host_key /fw; fi; 


#default mac (petalinux plus 1)
MAC_ADDR="00:0A:35:00:1E:54" 
#test for file existing

if [ -e /fw/mac.dat ]; then
    MAC_ADDR=$(cat /fw/mac.dat)
fi

echo "Using mac address: " $MAC_ADDR
#change address
ifconfig eth0 down
ifconfig eth0 hw ether $MAC_ADDR
ifconfig eth0 up


