#!/usr/bin/env python

import sys

outfileName = "petalinux-user-image.bbappend"
inFileName = "users.dat"

#Open the file
file = open(inFileName, "r")

#Read all file lines
inputLines = file.readlines()
length = len(inputLines)

#Close the file
file.close()

#manipulate inputLines
user_lines = []
for line in inputLines:
    #clean up line endings
    line = line.rstrip("\n")
    line = line.rstrip("\r")
    line = line.rstrip(" ")

    #check that we have to entries (username and password)
    if len(line.split()) < 2:
        sys.exit("Invalid line in input file");

    #get values
    username = line.split()[0]  #first value is username
    password = line.split()[1]  #second value is password

    if username == "root":
        user_lines.append("usermod -P " + password + " " + username + " ; \\\n")
    else:                                           
        user_lines.append("useradd -P " + password + " " + username + " ; \\\n")

    if len(line.split()) > 2:
        user_lines.append("usermod -a -G ")
        for group in line.split()[2:]:
            user_lines.append(group + " ")
        user_lines.append(username+" ; \\\n");

        



#Create new file for new structure
outFile = open(outfileName, "w")

#file header
outFile.write("# petalinux-user-image.bbapend content\n")
outFile.write("inherit extrausers\n")
outFile.write("EXTRA_USERS_PARAMS = \"\\\n")

#write data in new format
outFile.writelines(user_lines)

#trailer
outFile.write("\"\n")

#close new file
outFile.close
