add wave -position insertpoint  \
sim:/tb_lpgbt_symmetric/g_DATARATE \
sim:/tb_lpgbt_symmetric/g_FEC \
sim:/tb_lpgbt_symmetric/g_PAYLOAD_LENGTH \
sim:/tb_lpgbt_symmetric/TEST_BENCH_STATUS_O \
sim:/tb_lpgbt_symmetric/FECMONITOR_O \
sim:/tb_lpgbt_symmetric/PRBSMONITOR_O \
sim:/tb_lpgbt_symmetric/common_clk_mgt \
sim:/tb_lpgbt_symmetric/prbsgen_strobe_cntr \
sim:/tb_lpgbt_symmetric/prbsgen_strobe \
sim:/tb_lpgbt_symmetric/prbsgen_reset \
sim:/tb_lpgbt_symmetric/prbsgen_seed \
sim:/tb_lpgbt_symmetric/prbsgen_load \
sim:/tb_lpgbt_symmetric/prbsgen_frame \
sim:/tb_lpgbt_symmetric/Tx_reset \
sim:/tb_lpgbt_symmetric/Tx_tx_strobe \
sim:/tb_lpgbt_symmetric/Tx_tx_data \
sim:/tb_lpgbt_symmetric/Tx_tx_ec \
sim:/tb_lpgbt_symmetric/Tx_tx_ic \
sim:/tb_lpgbt_symmetric/Tx_tx_word \
sim:/tb_lpgbt_symmetric/Tx_scrambler_bypass \
sim:/tb_lpgbt_symmetric/Tx_interleaver_bypass \
sim:/tb_lpgbt_symmetric/Tx_tx_error \
sim:/tb_lpgbt_symmetric/channel_reset \
sim:/tb_lpgbt_symmetric/channel_ready \
sim:/tb_lpgbt_symmetric/channel_rx_data \
sim:/tb_lpgbt_symmetric/channel_data \
sim:/tb_lpgbt_symmetric/channel_bitslide_r \
sim:/tb_lpgbt_symmetric/channel_bitslip_position \
sim:/tb_lpgbt_symmetric/channel_rx_frame_reset_phy \
sim:/tb_lpgbt_symmetric/Rx_uplinkClkOutEn \
sim:/tb_lpgbt_symmetric/Rx_uplinkRst_n \
sim:/tb_lpgbt_symmetric/Rx_mgt_word \
sim:/tb_lpgbt_symmetric/Rx_USErData \
sim:/tb_lpgbt_symmetric/Rx_EcData \
sim:/tb_lpgbt_symmetric/Rx_IcData \
sim:/tb_lpgbt_symmetric/Rx_bypassInterleaver \
sim:/tb_lpgbt_symmetric/Rx_bypassFECEncoder \
sim:/tb_lpgbt_symmetric/Rx_bypassScrambler \
sim:/tb_lpgbt_symmetric/Rx_mgt_bitslipCtrl \
sim:/tb_lpgbt_symmetric/Rx_dataCorrected \
sim:/tb_lpgbt_symmetric/Rx_IcCorrected \
sim:/tb_lpgbt_symmetric/Rx_EcCorrected \
sim:/tb_lpgbt_symmetric/Rx_rdy \
sim:/tb_lpgbt_symmetric/prbschk_reset \
sim:/tb_lpgbt_symmetric/prbschk_frame \
sim:/tb_lpgbt_symmetric/prbschk_strobe \
sim:/tb_lpgbt_symmetric/prbschk_gen \
sim:/tb_lpgbt_symmetric/prbschk_error \
sim:/tb_lpgbt_symmetric/prbschk_locked