AXI_CONTROL_SETS:
  AXI_MASTER_CTRL:
      axi_interconnect: "${::AXI_INTERCONNECT_NAME}"
      axi_clk: "${::AXI_MASTER_CLK}"
      axi_rstn: "${::AXI_PRIMARY_SLAVE_RSTN}"
      axi_freq: "${::AXI_MASTER_CLK_FREQ}"
  AXI_C2C_CTRL:
      axi_interconnect: "${::AXI_C2C_INTERCONNECT_NAME}"
      axi_clk: "${::AXI_MASTER_CLK}"
      axi_rstn: "${::AXI_C2C_SLAVE_RSTN}"
      axi_freq: "${::AXI_MASTER_CLK_FREQ}"

AXI_SLAVES:
  C2C1:
    TCL_CALL:
      command: "AXI_C2C_MASTER"
      device_name: "C2C1"
      primary_serdes: "1"
      init_clk: "${::INIT_CLK}"
      refclk_freq: "100"
      irq_port: "${::IRQ0_INTR_CTRL}"
      speed: 5
      axi_control: "${::AXI_C2C_CTRL}"
      addr:
        offset: 0xB0000000
        range: "16M"

    SUB_SLAVES:
      C2C1B:
        TCL_CALL:
          command: "AXI_C2C_MASTER"
          device_name: "C2C1B"
          primary_serdes: "C2C1_PHY"
          init_clk: "${::INIT_CLK}"
          refclk_freq: "100"
          irq_port: "${::IRQ0_INTR_CTRL}"
          speed: 5
          axi_control: "${::AXI_C2C_CTRL}"
          addr_lite:
            offset: 0xB1000000
            range: "16M"    
      C2C2:
        TCL_CALL:
          command: "AXI_C2C_MASTER"
          device_name: "C2C2"
          axi_control: "${::AXI_C2C_CTRL}"
          primary_serdes: "C2C1_PHY"
          init_clk: "${::INIT_CLK}"
          irq_port: "${::IRQ0_INTR_CTRL}"
          speed: 5
          refclk_freq: "100"
          addr:
            offset: 0xB2000000
            range: "16M"

        SUB_SLAVES:
          C2C2B:
            TCL_CALL:
              command: "AXI_C2C_MASTER"
              device_name: "C2C2B"
              axi_control: "${::AXI_C2C_CTRL}"
              primary_serdes: "C2C1_PHY"
              init_clk: "${::INIT_CLK}"
              irq_port: "${::IRQ0_INTR_CTRL}"
              refclk_freq: "100"
              speed: 5
              addr_lite:
                offset: 0xB3000000
                range: "16M"
              SUB_SLAVES:    
                C2C2_AXI_FW:
                  TCL_CALL:
                    command: "AXI_IP_AXI_FW"
                    axi_fw_bus: "/C2C2/s_axi"
                    axi_control: "${::AXI_C2C_CTRL}"
                  XML:
                    - "address_table/modules/C2C2_AXI_FW.xml"
                  UHAL_BASE: 0x13000000
                C2C2_AXILITE_FW:
                  TCL_CALL:
                    command: "AXI_IP_AXI_FW"
                    axi_fw_bus: "/C2C2B/s_axi_lite"
                    axi_control: "${::AXI_C2C_CTRL}"
                  XML:
                    - "address_table/modules/C2C2_AXILITE_FW.xml"
                  UHAL_BASE: 0x14000000
      C2C1_AXI_FW:
        TCL_CALL:
          command: "AXI_IP_AXI_FW"
          axi_fw_bus: "/C2C1/s_axi"
          axi_control: "${::AXI_C2C_CTRL}"
        XML:
          - "address_table/modules/C2C1_AXI_FW.xml"
        UHAL_BASE: 0x0D000000
      C2C1_AXILITE_FW:
        TCL_CALL:
          command: "AXI_IP_AXI_FW"
          axi_fw_bus: "/C2C1B/s_axi_lite"
          axi_control: "${::AXI_C2C_CTRL}"
        XML:
          - "address_table/modules/C2C1_AXILITE_FW.xml"
        UHAL_BASE: 0x0E000000


  PL_MEM:
    TCL_CALL:
      command: "AXI_IP_BRAM"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: -1
        range: "8K"
    XML:
      - "address_table/modules/PL_MEM.xml"
      - "address_table/modules/PL_MEM_CM.xml"
      - "address_table/modules/I2C_REGULATOR_MONITOR.xml"
    UHAL_BASE: 0x15000000
    
  SI:
    TCL_CALL:
      command: "AXI_IP_I2C"
      axi_control: "${::AXI_MASTER_CTRL}"

  SERV:
    TCL_CALL:
      command: "AXI_PL_DEV_CONNECT"
      axi_control: "${::AXI_MASTER_CTRL}"
    XML:
      - "address_table/modules/SERV_rev2.xml"
    UHAL_BASE: 0x04000000
    HDL:
      map_template: "axi_generic/template_map_withbram.vhd"

  PLXVC:
    TCL_CALL:
      command: "AXI_PL_DEV_CONNECT"
      axi_control: "${::AXI_MASTER_CTRL}"
    XML:
      - "address_table/modules/plXVC_rev2.xml"
      - "address_table/modules/plXVC_single.xml"
    UHAL_BASE: 0x06000000
    HDL: 
      map_template: "axi_generic/template_map_withbram.vhd"

  SLAVE_I2C:
    TCL_CALL:
      command: "AXI_PL_DEV_CONNECT"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: -1
        range: "8K"
    XML:
      - "address_table/modules/SLAVE_I2C.xml"
    UHAL_BASE: 0x05000000

  CM:
    TCL_CALL:
      command: "AXI_PL_DEV_CONNECT"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: 0xA0100000
        range: "128K"
    XML:
      - "address_table/modules/CM_USP.xml"
      - "address_table/modules/CM_single_USP.xml"
      - "address_table/modules/CM_C2C_USP.xml"
      - "address_table/modules/CM_CTRL.xml"
      - "address_table/modules/CM_C2C_Status.xml"
      - "address_table/modules/CM_C2C_DEBUG_USP.xml"
      - "address_table/modules/CM_Mon.xml"
      - "address_table/modules/CM_C2C_CNT.xml"
      - "address_table/modules/AXI_ADDR_INFO.xml"
      - "address_table/modules/CM_BRIDGE_INFO.xml"
      - "address_table/modules/DRP_USP_GTH.xml"
    UHAL_BASE: 0x03000000
    HDL: 
      map_template: "axi_generic/template_map_withbram.vhd"

  SM_INFO:
    TCL_CALL:
      command: "AXI_PL_DEV_CONNECT"
      axi_control: "${::AXI_MASTER_CTRL}"
    XML:
      - "address_table/modules/FW_INFO.xml"
    UHAL_BASE: 0x0A000000
    HDL: 
      map_template: "axi_generic/template_map_withbram.vhd"

  MONITOR:
    TCL_CALL:
      command: "AXI_IP_SYS_MGMT"
      axi_control: "${::AXI_MASTER_CTRL}"
      enable_i2c_pins: 0
    XML:
      - "address_table/modules/MONITOR_USP.xml"
    UHAL_BASE: 0x0B000000

  CM1_UART:
    TCL_CALL:
      command: "AXI_IP_UART"
      baud_rate: "115200"
      irq_port: "${::IRQ0_INTR_CTRL}"
      axi_control: "${::AXI_MASTER_CTRL}"
      remote_slave: "0"
      dt_data: "port-number = <1>;"

  CM2_UART:
    TCL_CALL:
      command: "AXI_IP_UART"
      baud_rate: "115200"
      irq_port: "${::IRQ0_INTR_CTRL}"
      axi_control: "${::AXI_MASTER_CTRL}"
      remote_slave: "0"
      dt_data: "port-number = <2>;"


  CM_PB_UART:
    TCL_CALL:
      command: "AXI_IP_UART"
      baud_rate: "115200"
      irq_port: "${::IRQ0_INTR_CTRL}"
      axi_control: "${::AXI_MASTER_CTRL}"
      remote_slave: "0"
      dt_data: "port-number = <100>;"



  ESM_UART:
    TCL_CALL:
      command: "AXI_IP_UART"
      baud_rate: "115200"
      irq_port: "${::IRQ0_INTR_CTRL}"
      axi_control: "${::AXI_MASTER_CTRL}"
      remote_slave: "0"
      dt_data: "port-number = <3>;"


  AXI_MON:
    TCL_CALL:
      command: "AXI_IP_AXI_MONITOR"
      axi_control: "${::AXI_C2C_CTRL}"
      core_clk: "${::AXI_MASTER_CLK}"
      core_rstn: "${::AXI_PRIMARY_MASTER_RSTN}"
      mon_axi:
       - "${::ZYNQ_NAME}/M_AXI_HPM0_FPD"
       - "${::ZYNQ_NAME}/M_AXI_HPM1_FPD"
      mon_axi_clk:
       - ${::AXI_MASTER_CLK}
       - ${::AXI_MASTER_CLK}
      mon_axi_rstn: "${::AXI_PRIMARY_MASTER_RSTN} ${::AXI_C2C_MASTER_RSTN}"

    XML:
      - "address_table/modules/AXI_MONITOR.xml"
      - "address_table/modules/AXI_MONITOR_COUNTER.xml"
    UHAL_BASE: 0x1F000000


  MEM_TEST:
    TCL_CALL:
      command: "AXI_PL_DEV_CONNECT"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "-1"
        range: "8K"
    XML:
      - "address_table/modules/MEM_TEST.xml"
    UHAL_BASE: 0x0F000000
    HDL: 
      map_template: "axi_generic/template_map_withbram.vhd"

  IRQ_CTRL:
    XML:
      - "address_table/modules/INTERRUPT_CONTROLLER.xml"
    UHAL_BASE: 0x16000000

  INT_AXI_FW:
    TCL_CALL:
      command: "AXI_IP_AXI_FW"
      axi_fw_bus: "/${::ZYNQ_NAME}/M_AXI_HPM0_FPD"
      axi_control: "${::AXI_C2C_CTRL}"
    XML:
      - "address_table/modules/INT_AXI_FW.xml"
    UHAL_BASE: 0x20000000
  IRQ_CTRL:
    XML:
      - "address_table/modules/INTERRUPT_CONTROLLER.xml"
    UHAL_BASE: 0x16000000
  
XVC_LOCAL:
  TCL_CALL:
    command: "AXI_IP_LOCAL_XVC"
    axi_control: "${::AXI_MASTER_CTRL}"
  XML:
    - "address_table/modules/XVC.xml"
  UHAL_BASE: 0x0C000000

CORES:
  onboardclk:
    TCL_CALL:
      command: BuildClockWizard
      in_clk_type: Differential_clock_capable_pin
      in_clk_freq_MHZ: 100
      out_clks:
        1: 200
        2: 71.427856
