create_clock -period 5.000 [get_ports {clk_in1_p}]
create_generated_clock -source [get_ports -no_traverse clk_in1_p] -edges {1 2 3} -edge_shift {0.000 7.500 15.000} [get_ports -no_traverse {clk_50MHz}]
create_generated_clock -source [get_ports -no_traverse clk_in1_p] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports -no_traverse {clk_200MHz}]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet clk_in1_n]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet clk_in1_n]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet clk_in1_p]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet clk_in1_p]
set_property -quiet IS_IP_OOC_CELL TRUE [get_cells -of [get_ports -no_traverse -quiet clk_200MHz]]
