#-----------------------------------------------------------------
#--- Calculate probes
#-----------------------------------------------------------------
default_probes = {
  # Master 0  
  "master_clk_offset_locked_1"                                  : { "dir" :  "in", "size" :  1}                     ,  
  "prbschk_master_locked_sync_1"                                : { "dir" :  "in", "size" :  1}                     ,    
  "master_firefly_modprs_b_sync_1"                              : { "dir" :  "in", "size" :  1}                     , 
  "master_firefly_int_b_sync_1"                                  : { "dir" :  "in", "size" :  1}                    , 

  "master_core_stat[0][phase_cdc40_rx]"                         : { "dir" :  "in", "size" :  3}                     , 
  "master_core_stat[0][phase_cdc40_tx]"                         : { "dir" :  "in", "size" : 10}                     , 
  "master_core_stat[0][rx_fec_corrected_latched]"               : { "dir" :  "in", "size" :  1}                     ,  
  "master_core_stat[0][rx_frame_locked]"                        : { "dir" :  "in", "size" :  1}                     ,        
  "master_core_stat[0][mgt_txpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[0][mgt_rxpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[0][mgt_buffbypass_rx_done]"                 : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[0][mgt_buffbypass_rx_error]"                : { "dir" :  "in", "size" :  1}                     ,
  "master_core_stat[0][mgt_powergood]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[0][mgt_reset_tx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[0][mgt_reset_rx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[0][mgt_rxpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[0][mgt_txpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[0][mgt_tx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[0][mgt_rx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[0][mgt_rxprbserr]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[0][mgt_rxprbslocked]"                       : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[0][mgt_drprdy_latched]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[0][mgt_drpdo]"                              : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[0][mgt_hptd_tx_pi_phase]"                   : { "dir" :  "in", "size" :  7}                     , 
  "master_core_stat[0][mgt_hptd_tx_fifo_fill_pd]"               : { "dir" :  "in", "size" : 32}                     , 
  "master_core_stat[0][mgt_hptd_ps_done_latched]"               : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[0][mgt_rxeq_dmonitor]"                      : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[0][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[0][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[0][tx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[0][rx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[0][rx_data_not_idle]"                       : { "dir" :  "in", "size" : 1}                      ,
  
  "master_tclink_stat[0][tclink_phase_detector]"                : { "dir" :  "in", "size" : 32}                     ,
  "master_tclink_stat[0][tclink_error_controller]"              : { "dir" :  "in", "size" : 48}                     ,
  "master_tclink_stat[0][tclink_phase_acc]"                     : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[0][tclink_operation_error]"               : { "dir" :  "in", "size" :  1}                     ,
  "master_tclink_stat[0][tclink_debug_tester_data_read]"        : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[0][tclink_loop_closed]"                   : { "dir" :  "in", "size" : 1}                     ,
  
  "master_firefly_reset_b_1"                                    : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_firefly_modsel_b_1"                                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  

  "master_core_ctrl[0][mgt_reset_all]"                          : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[0][mgt_reset_tx_pll_and_datapath]"          : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[0][mgt_reset_tx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[0][mgt_reset_rx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_stat[0][channel_ready]"                          : { "dir" :  "in", "size" : 1}                      ,     
  "master_core_stat[0][channel_controller_state]"                      : { "dir" :  "in", "size" : 17}                     ,     
  "master_core_stat[0][channel_controller_running]"                    : { "dir" :  "in", "size" : 1}                     ,   
  "master_core_ctrl[0][channel_controller_reset]"                      : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[0][channel_controller_enable]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[0][channel_controller_gentle]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  
  
  "master_core_ctrl[0][phase_cdc40_rx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[0][phase_cdc40_rx_calib]"                   : { "dir" : "out", "size" :  3, "init" :        0x0}, 
  "master_core_ctrl[0][phase_cdc40_tx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[0][phase_cdc40_tx_calib]"                   : { "dir" : "out", "size" : 10, "init" :        0x0}, 
  "master_core_ctrl[0][rx_fec_corrected_clear]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},   
  "master_core_ctrl[0][mgt_txpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[0][mgt_rxpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[0][mgt_loopback]"                           : { "dir" : "out", "size" :  3, "init" :        0x0},
  "master_core_ctrl[0][mgt_txprbsforceerr]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[0][mgt_txprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[0][mgt_rxprbscntreset]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[0][mgt_rxprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[0][mgt_drpwe]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[0][mgt_drpen]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[0][mgt_drpaddr]"                            : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_core_ctrl[0][mgt_drpdi]"                              : { "dir" : "out", "size" : 16, "init" :        0x0},  
  "master_core_ctrl[0][mgt_hptd_tx_pi_phase_calib]"             : { "dir" : "out", "size" :  7, "init" :        0x0}, 
  "master_core_ctrl[0][mgt_hptd_tx_ui_align_calib]"             : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[0][mgt_hptd_ps_strobe]"                     : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[0][mgt_hptd_ps_inc_ndec]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[0][mgt_hptd_ps_phase_step]"                 : { "dir" : "out", "size" :  4, "init" :        0x0}, 
  "master_core_ctrl[0][mgt_rxeq_rxlpmgcovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[0][mgt_rxeq_rxlpmhfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[0][mgt_rxeq_rxlpmlfklovrden]"               : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[0][mgt_rxeq_rxlpmosovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[0][mgt_rxeq_rxlpmen]"                       : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[0][mgt_rxeq_rxdfelfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[0][mgt_rxeq_rxdfelpmreset]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[0][mgt_rxeq_rxdfeutovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[0][mgt_rxeq_rxdfevpovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[0][mgt_rxeq_rxdfeagcovrden]"                : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[0][mgt_rxeq_rxosovrden]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  
  "master_tclink_ctrl[0][tclink_close_loop]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[0][tclink_offset_error]"                  : { "dir" : "out", "size" : 48, "init" :        0x0},
  "master_tclink_ctrl[0][tclink_metastability_deglitch]"        : { "dir" : "out", "size" : 16, "init" :     0x0052},
  "master_tclink_ctrl[0][tclink_phase_detector_navg]"           : { "dir" : "out", "size" : 12, "init" :      0x040},
  "master_tclink_ctrl[0][tclink_modulo_carrier_period]"         : { "dir" : "out", "size" : 48, "init" : 0x00007ff48348},
  "master_tclink_ctrl[0][tclink_Aie]"                           : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_tclink_ctrl[0][tclink_Aie_enable]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[0][tclink_Ape]"                           : { "dir" : "out", "size" :  4, "init" :        0xe},
  "master_tclink_ctrl[0][tclink_sigma_delta_clk_div]"           : { "dir" : "out", "size" : 16, "init" :     0x0197},
  "master_tclink_ctrl[0][tclink_enable_mirror]"                 : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_tclink_ctrl[0][tclink_Adco]"                          : { "dir" : "out", "size" : 48, "init" : 0x0000000ffe90},
  "master_tclink_ctrl[0][tclink_debug_tester_enable_stimulis]"  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[0][tclink_debug_tester_fcw]"              : { "dir" : "out", "size" : 10, "init" :      0x002},
  "master_tclink_ctrl[0][tclink_debug_tester_nco_scale]"        : { "dir" : "out", "size" :  5, "init" :       0x14},
  "master_tclink_ctrl[0][tclink_debug_tester_enable_stock_out]" : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[0][tclink_debug_tester_addr_read]"        : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_tclink_ctrl[0][tclink_master_rx_ui_period]"           : { "dir" : "out", "size" : 48, "init" : 0x000003ffa41a},

  # Master 1
  "master_clk_offset_locked_2"                                  : { "dir" :  "in", "size" :  1}                     ,  
  "prbschk_master_locked_sync_2"                                : { "dir" :  "in", "size" :  1}                     ,    
  "master_firefly_modprs_b_sync_2"                              : { "dir" :  "in", "size" :  1}                     , 
  "master_firefly_int_b_sync_2"                                  : { "dir" :  "in", "size" :  1}                    , 

  "master_core_stat[1][phase_cdc40_rx]"                         : { "dir" :  "in", "size" :  3}                     , 
  "master_core_stat[1][phase_cdc40_tx]"                         : { "dir" :  "in", "size" : 10}                     , 
  "master_core_stat[1][rx_fec_corrected_latched]"               : { "dir" :  "in", "size" :  1}                     ,  
  "master_core_stat[1][rx_frame_locked]"                        : { "dir" :  "in", "size" :  1}                     ,        
  "master_core_stat[1][mgt_txpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[1][mgt_rxpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[1][mgt_buffbypass_rx_done]"                 : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[1][mgt_buffbypass_rx_error]"                : { "dir" :  "in", "size" :  1}                     ,
  "master_core_stat[1][mgt_powergood]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[1][mgt_reset_tx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[1][mgt_reset_rx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[1][mgt_rxpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[1][mgt_txpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[1][mgt_tx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[1][mgt_rx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[1][mgt_rxprbserr]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[1][mgt_rxprbslocked]"                       : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[1][mgt_drprdy_latched]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[1][mgt_drpdo]"                              : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[1][mgt_hptd_tx_pi_phase]"                   : { "dir" :  "in", "size" :  7}                     , 
  "master_core_stat[1][mgt_hptd_tx_fifo_fill_pd]"               : { "dir" :  "in", "size" : 32}                     , 
  "master_core_stat[1][mgt_hptd_ps_done_latched]"               : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[1][mgt_rxeq_dmonitor]"                      : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[1][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[1][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[1][tx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[1][rx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[1][rx_data_not_idle]"                       : { "dir" :  "in", "size" : 1}                      ,
  
  "master_tclink_stat[1][tclink_phase_detector]"                : { "dir" :  "in", "size" : 32}                     ,
  "master_tclink_stat[1][tclink_error_controller]"              : { "dir" :  "in", "size" : 48}                     ,
  "master_tclink_stat[1][tclink_phase_acc]"                     : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[1][tclink_operation_error]"               : { "dir" :  "in", "size" :  1}                     ,
  "master_tclink_stat[1][tclink_debug_tester_data_read]"        : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[1][tclink_loop_closed]"                   : { "dir" :  "in", "size" : 1}                     ,
  
  "master_firefly_reset_b_2"                                    : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_firefly_modsel_b_2"                                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[1][mgt_reset_all]"                          : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[1][mgt_reset_tx_pll_and_datapath]"          : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[1][mgt_reset_tx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[1][mgt_reset_rx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_stat[1][channel_ready]"                          : { "dir" :  "in", "size" : 1}                      ,     
  "master_core_stat[1][channel_controller_state]"                      : { "dir" :  "in", "size" : 17}                     ,     
  "master_core_stat[1][channel_controller_running]"                    : { "dir" :  "in", "size" : 1}                     ,   
  "master_core_ctrl[1][channel_controller_reset]"                      : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[1][channel_controller_enable]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[1][channel_controller_gentle]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},

  "master_core_ctrl[1][phase_cdc40_rx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[1][phase_cdc40_rx_calib]"                   : { "dir" : "out", "size" :  3, "init" :        0x0}, 
  "master_core_ctrl[1][phase_cdc40_tx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[1][phase_cdc40_tx_calib]"                   : { "dir" : "out", "size" : 10, "init" :        0x0}, 
  "master_core_ctrl[1][rx_fec_corrected_clear]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},   
  "master_core_ctrl[1][mgt_txpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[1][mgt_rxpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[1][mgt_loopback]"                           : { "dir" : "out", "size" :  3, "init" :        0x0},
  "master_core_ctrl[1][mgt_txprbsforceerr]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[1][mgt_txprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[1][mgt_rxprbscntreset]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[1][mgt_rxprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[1][mgt_drpwe]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[1][mgt_drpen]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[1][mgt_drpaddr]"                            : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_core_ctrl[1][mgt_drpdi]"                              : { "dir" : "out", "size" : 16, "init" :        0x0},  
  "master_core_ctrl[1][mgt_hptd_tx_pi_phase_calib]"             : { "dir" : "out", "size" :  7, "init" :        0x0}, 
  "master_core_ctrl[1][mgt_hptd_tx_ui_align_calib]"             : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[1][mgt_hptd_ps_strobe]"                     : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[1][mgt_hptd_ps_inc_ndec]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[1][mgt_hptd_ps_phase_step]"                 : { "dir" : "out", "size" :  4, "init" :        0x0}, 
  "master_core_ctrl[1][mgt_rxeq_rxlpmgcovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[1][mgt_rxeq_rxlpmhfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[1][mgt_rxeq_rxlpmlfklovrden]"               : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[1][mgt_rxeq_rxlpmosovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[1][mgt_rxeq_rxlpmen]"                       : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[1][mgt_rxeq_rxdfelfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[1][mgt_rxeq_rxdfelpmreset]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[1][mgt_rxeq_rxdfeutovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[1][mgt_rxeq_rxdfevpovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[1][mgt_rxeq_rxdfeagcovrden]"                : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[1][mgt_rxeq_rxosovrden]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  
  "master_tclink_ctrl[1][tclink_close_loop]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[1][tclink_offset_error]"                  : { "dir" : "out", "size" : 48, "init" :        0x0},
  "master_tclink_ctrl[1][tclink_metastability_deglitch]"        : { "dir" : "out", "size" : 16, "init" :     0x0052},
  "master_tclink_ctrl[1][tclink_phase_detector_navg]"           : { "dir" : "out", "size" : 12, "init" :      0x040},
  "master_tclink_ctrl[1][tclink_modulo_carrier_period]"         : { "dir" : "out", "size" : 48, "init" : 0x00007ff48348},
  "master_tclink_ctrl[1][tclink_Aie]"                           : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_tclink_ctrl[1][tclink_Aie_enable]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[1][tclink_Ape]"                           : { "dir" : "out", "size" :  4, "init" :        0xe},
  "master_tclink_ctrl[1][tclink_sigma_delta_clk_div]"           : { "dir" : "out", "size" : 16, "init" :     0x0197},
  "master_tclink_ctrl[1][tclink_enable_mirror]"                 : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_tclink_ctrl[1][tclink_Adco]"                          : { "dir" : "out", "size" : 48, "init" : 0x0000000ffe90},
  "master_tclink_ctrl[1][tclink_debug_tester_enable_stimulis]"  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[1][tclink_debug_tester_fcw]"              : { "dir" : "out", "size" : 10, "init" :      0x002},
  "master_tclink_ctrl[1][tclink_debug_tester_nco_scale]"        : { "dir" : "out", "size" :  5, "init" :       0x14},
  "master_tclink_ctrl[1][tclink_debug_tester_enable_stock_out]" : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[1][tclink_debug_tester_addr_read]"        : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_tclink_ctrl[1][tclink_master_rx_ui_period]"           : { "dir" : "out", "size" : 48, "init" : 0x000003ffa41a},

  # Master 2  
  "master_clk_offset_locked_3"                                  : { "dir" :  "in", "size" :  1}                     ,  
  "prbschk_master_locked_sync_3"                                : { "dir" :  "in", "size" :  1}                     ,    
  "master_firefly_modprs_b_sync_3"                              : { "dir" :  "in", "size" :  1}                     , 
  "master_firefly_int_b_sync_3"                                  : { "dir" :  "in", "size" :  1}                    , 

  "master_core_stat[2][phase_cdc40_rx]"                         : { "dir" :  "in", "size" :  3}                     , 
  "master_core_stat[2][phase_cdc40_tx]"                         : { "dir" :  "in", "size" : 10}                     , 
  "master_core_stat[2][rx_fec_corrected_latched]"               : { "dir" :  "in", "size" :  1}                     ,  
  "master_core_stat[2][rx_frame_locked]"                        : { "dir" :  "in", "size" :  1}                     ,        
  "master_core_stat[2][mgt_txpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[2][mgt_rxpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[2][mgt_buffbypass_rx_done]"                 : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[2][mgt_buffbypass_rx_error]"                : { "dir" :  "in", "size" :  1}                     ,
  "master_core_stat[2][mgt_powergood]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[2][mgt_reset_tx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[2][mgt_reset_rx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[2][mgt_rxpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[2][mgt_txpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[2][mgt_tx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[2][mgt_rx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[2][mgt_rxprbserr]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[2][mgt_rxprbslocked]"                       : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[2][mgt_drprdy_latched]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[2][mgt_drpdo]"                              : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[2][mgt_hptd_tx_pi_phase]"                   : { "dir" :  "in", "size" :  7}                     , 
  "master_core_stat[2][mgt_hptd_tx_fifo_fill_pd]"               : { "dir" :  "in", "size" : 32}                     , 
  "master_core_stat[2][mgt_hptd_ps_done_latched]"               : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[2][mgt_rxeq_dmonitor]"                      : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[2][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[2][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[2][tx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[2][rx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[2][rx_data_not_idle]"                       : { "dir" :  "in", "size" : 1}                      ,
  
  "master_tclink_stat[2][tclink_phase_detector]"                : { "dir" :  "in", "size" : 32}                     ,
  "master_tclink_stat[2][tclink_error_controller]"              : { "dir" :  "in", "size" : 48}                     ,
  "master_tclink_stat[2][tclink_phase_acc]"                     : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[2][tclink_operation_error]"               : { "dir" :  "in", "size" :  1}                     ,
  "master_tclink_stat[2][tclink_debug_tester_data_read]"        : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[2][tclink_loop_closed]"                   : { "dir" :  "in", "size" : 1}                     ,
  
  
  "master_firefly_reset_b_3"                                    : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_firefly_modsel_b_3"                                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[2][mgt_reset_all]"                          : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[2][mgt_reset_tx_pll_and_datapath]"          : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[2][mgt_reset_tx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[2][mgt_reset_rx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_stat[2][channel_ready]"                          : { "dir" :  "in", "size" : 1}                      ,     
  "master_core_stat[2][channel_controller_state]"                      : { "dir" :  "in", "size" : 17}                     ,     
  "master_core_stat[2][channel_controller_running]"                    : { "dir" :  "in", "size" : 1}                     ,   
  "master_core_ctrl[2][channel_controller_reset]"                      : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[2][channel_controller_enable]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[2][channel_controller_gentle]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},

  "master_core_ctrl[2][phase_cdc40_rx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[2][phase_cdc40_rx_calib]"                   : { "dir" : "out", "size" :  3, "init" :        0x0}, 
  "master_core_ctrl[2][phase_cdc40_tx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[2][phase_cdc40_tx_calib]"                   : { "dir" : "out", "size" : 10, "init" :        0x0}, 
  "master_core_ctrl[2][rx_fec_corrected_clear]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},   
  "master_core_ctrl[2][mgt_txpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[2][mgt_rxpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[2][mgt_loopback]"                           : { "dir" : "out", "size" :  3, "init" :        0x0},
  "master_core_ctrl[2][mgt_txprbsforceerr]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[2][mgt_txprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[2][mgt_rxprbscntreset]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[2][mgt_rxprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[2][mgt_drpwe]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[2][mgt_drpen]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[2][mgt_drpaddr]"                            : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_core_ctrl[2][mgt_drpdi]"                              : { "dir" : "out", "size" : 16, "init" :        0x0},  
  "master_core_ctrl[2][mgt_hptd_tx_pi_phase_calib]"             : { "dir" : "out", "size" :  7, "init" :        0x0}, 
  "master_core_ctrl[2][mgt_hptd_tx_ui_align_calib]"             : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[2][mgt_hptd_ps_strobe]"                     : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[2][mgt_hptd_ps_inc_ndec]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[2][mgt_hptd_ps_phase_step]"                 : { "dir" : "out", "size" :  4, "init" :        0x0}, 
  "master_core_ctrl[2][mgt_rxeq_rxlpmgcovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[2][mgt_rxeq_rxlpmhfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[2][mgt_rxeq_rxlpmlfklovrden]"               : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[2][mgt_rxeq_rxlpmosovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[2][mgt_rxeq_rxlpmen]"                       : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[2][mgt_rxeq_rxdfelfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[2][mgt_rxeq_rxdfelpmreset]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[2][mgt_rxeq_rxdfeutovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[2][mgt_rxeq_rxdfevpovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[2][mgt_rxeq_rxdfeagcovrden]"                : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[2][mgt_rxeq_rxosovrden]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  
  "master_tclink_ctrl[2][tclink_close_loop]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[2][tclink_offset_error]"                  : { "dir" : "out", "size" : 48, "init" :        0x0},
  "master_tclink_ctrl[2][tclink_metastability_deglitch]"        : { "dir" : "out", "size" : 16, "init" :     0x0052},
  "master_tclink_ctrl[2][tclink_phase_detector_navg]"           : { "dir" : "out", "size" : 12, "init" :      0x040},
  "master_tclink_ctrl[2][tclink_modulo_carrier_period]"         : { "dir" : "out", "size" : 48, "init" : 0x00007ff48348},
  "master_tclink_ctrl[2][tclink_Aie]"                           : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_tclink_ctrl[2][tclink_Aie_enable]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[2][tclink_Ape]"                           : { "dir" : "out", "size" :  4, "init" :        0xe},
  "master_tclink_ctrl[2][tclink_sigma_delta_clk_div]"           : { "dir" : "out", "size" : 16, "init" :     0x0197},
  "master_tclink_ctrl[2][tclink_enable_mirror]"                 : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_tclink_ctrl[2][tclink_Adco]"                          : { "dir" : "out", "size" : 48, "init" : 0x0000000ffe90},
  "master_tclink_ctrl[2][tclink_debug_tester_enable_stimulis]"  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[2][tclink_debug_tester_fcw]"              : { "dir" : "out", "size" : 10, "init" :      0x002},
  "master_tclink_ctrl[2][tclink_debug_tester_nco_scale]"        : { "dir" : "out", "size" :  5, "init" :       0x14},
  "master_tclink_ctrl[2][tclink_debug_tester_enable_stock_out]" : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[2][tclink_debug_tester_addr_read]"        : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_tclink_ctrl[2][tclink_master_rx_ui_period]"           : { "dir" : "out", "size" : 48, "init" : 0x000003ffa41a},

  # Master 3 
  "master_clk_offset_locked_4"                                  : { "dir" :  "in", "size" :  1}                     ,  
  "prbschk_master_locked_sync_4"                                : { "dir" :  "in", "size" :  1}                     ,    
  "master_firefly_modprs_b_sync_4"                              : { "dir" :  "in", "size" :  1}                     , 
  "master_firefly_int_b_sync_4"                                  : { "dir" :  "in", "size" :  1}                    , 

  "master_core_stat[3][phase_cdc40_rx]"                         : { "dir" :  "in", "size" :  3}                     , 
  "master_core_stat[3][phase_cdc40_tx]"                         : { "dir" :  "in", "size" : 10}                     , 
  "master_core_stat[3][rx_fec_corrected_latched]"               : { "dir" :  "in", "size" :  1}                     ,  
  "master_core_stat[3][rx_frame_locked]"                        : { "dir" :  "in", "size" :  1}                     ,        
  "master_core_stat[3][mgt_txpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[3][mgt_rxpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[3][mgt_buffbypass_rx_done]"                 : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[3][mgt_buffbypass_rx_error]"                : { "dir" :  "in", "size" :  1}                     ,
  "master_core_stat[3][mgt_powergood]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[3][mgt_reset_tx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[3][mgt_reset_rx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[3][mgt_rxpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[3][mgt_txpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[3][mgt_tx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[3][mgt_rx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[3][mgt_rxprbserr]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[3][mgt_rxprbslocked]"                       : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[3][mgt_drprdy_latched]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[3][mgt_drpdo]"                              : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[3][mgt_hptd_tx_pi_phase]"                   : { "dir" :  "in", "size" :  7}                     , 
  "master_core_stat[3][mgt_hptd_tx_fifo_fill_pd]"               : { "dir" :  "in", "size" : 32}                     , 
  "master_core_stat[3][mgt_hptd_ps_done_latched]"               : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[3][mgt_rxeq_dmonitor]"                      : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[3][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[3][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[3][tx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[3][rx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[3][rx_data_not_idle]"                       : { "dir" :  "in", "size" : 1}                      ,
  
  "master_tclink_stat[3][tclink_phase_detector]"                : { "dir" :  "in", "size" : 32}                     ,
  "master_tclink_stat[3][tclink_error_controller]"              : { "dir" :  "in", "size" : 48}                     ,
  "master_tclink_stat[3][tclink_phase_acc]"                     : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[3][tclink_operation_error]"               : { "dir" :  "in", "size" :  1}                     ,
  "master_tclink_stat[3][tclink_debug_tester_data_read]"        : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[3][tclink_loop_closed]"                   : { "dir" :  "in", "size" : 1}                     ,
  
  
  "master_firefly_reset_b_4"                                    : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_firefly_modsel_b_4"                                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[3][mgt_reset_all]"                          : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[3][mgt_reset_tx_pll_and_datapath]"          : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[3][mgt_reset_tx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[3][mgt_reset_rx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_stat[3][channel_ready]"                          : { "dir" :  "in", "size" : 1}                      ,     
  "master_core_stat[3][channel_controller_state]"                      : { "dir" :  "in", "size" : 17}                     ,     
  "master_core_stat[3][channel_controller_running]"                    : { "dir" :  "in", "size" : 1}                     ,   
  "master_core_ctrl[3][channel_controller_reset]"                      : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[3][channel_controller_enable]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[3][channel_controller_gentle]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},

  "master_core_ctrl[3][phase_cdc40_rx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[3][phase_cdc40_rx_calib]"                   : { "dir" : "out", "size" :  3, "init" :        0x0}, 
  "master_core_ctrl[3][phase_cdc40_tx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[3][phase_cdc40_tx_calib]"                   : { "dir" : "out", "size" : 10, "init" :        0x0}, 
  "master_core_ctrl[3][rx_fec_corrected_clear]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},   
  "master_core_ctrl[3][mgt_txpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[3][mgt_rxpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[3][mgt_loopback]"                           : { "dir" : "out", "size" :  3, "init" :        0x0},
  "master_core_ctrl[3][mgt_txprbsforceerr]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[3][mgt_txprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[3][mgt_rxprbscntreset]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[3][mgt_rxprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[3][mgt_drpwe]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[3][mgt_drpen]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[3][mgt_drpaddr]"                            : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_core_ctrl[3][mgt_drpdi]"                              : { "dir" : "out", "size" : 16, "init" :        0x0},  
  "master_core_ctrl[3][mgt_hptd_tx_pi_phase_calib]"             : { "dir" : "out", "size" :  7, "init" :        0x0}, 
  "master_core_ctrl[3][mgt_hptd_tx_ui_align_calib]"             : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[3][mgt_hptd_ps_strobe]"                     : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[3][mgt_hptd_ps_inc_ndec]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[3][mgt_hptd_ps_phase_step]"                 : { "dir" : "out", "size" :  4, "init" :        0x0}, 
  "master_core_ctrl[3][mgt_rxeq_rxlpmgcovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[3][mgt_rxeq_rxlpmhfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[3][mgt_rxeq_rxlpmlfklovrden]"               : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[3][mgt_rxeq_rxlpmosovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[3][mgt_rxeq_rxlpmen]"                       : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[3][mgt_rxeq_rxdfelfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[3][mgt_rxeq_rxdfelpmreset]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[3][mgt_rxeq_rxdfeutovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[3][mgt_rxeq_rxdfevpovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[3][mgt_rxeq_rxdfeagcovrden]"                : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[3][mgt_rxeq_rxosovrden]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  
  "master_tclink_ctrl[3][tclink_close_loop]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[3][tclink_offset_error]"                  : { "dir" : "out", "size" : 48, "init" :        0x0},
  "master_tclink_ctrl[3][tclink_metastability_deglitch]"        : { "dir" : "out", "size" : 16, "init" :     0x0052},
  "master_tclink_ctrl[3][tclink_phase_detector_navg]"           : { "dir" : "out", "size" : 12, "init" :      0x040},
  "master_tclink_ctrl[3][tclink_modulo_carrier_period]"         : { "dir" : "out", "size" : 48, "init" : 0x00007ff48348},
  "master_tclink_ctrl[3][tclink_Aie]"                           : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_tclink_ctrl[3][tclink_Aie_enable]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[3][tclink_Ape]"                           : { "dir" : "out", "size" :  4, "init" :        0xe},
  "master_tclink_ctrl[3][tclink_sigma_delta_clk_div]"           : { "dir" : "out", "size" : 16, "init" :     0x0197},
  "master_tclink_ctrl[3][tclink_enable_mirror]"                 : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_tclink_ctrl[3][tclink_Adco]"                          : { "dir" : "out", "size" : 48, "init" : 0x0000000ffe90},
  "master_tclink_ctrl[3][tclink_debug_tester_enable_stimulis]"  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[3][tclink_debug_tester_fcw]"              : { "dir" : "out", "size" : 10, "init" :      0x002},
  "master_tclink_ctrl[3][tclink_debug_tester_nco_scale]"        : { "dir" : "out", "size" :  5, "init" :       0x14},
  "master_tclink_ctrl[3][tclink_debug_tester_enable_stock_out]" : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[3][tclink_debug_tester_addr_read]"        : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_tclink_ctrl[3][tclink_master_rx_ui_period]"           : { "dir" : "out", "size" : 48, "init" : 0x000003ffa41a},
  
  # Master 4 
  "master_clk_offset_locked_5"                                  : { "dir" :  "in", "size" :  1}                     ,  
  "prbschk_master_locked_sync_5"                                : { "dir" :  "in", "size" :  1}                     ,    
  "master_firefly_modprs_b_sync_5"                              : { "dir" :  "in", "size" :  1}                     , 
  "master_firefly_int_b_sync_5"                                  : { "dir" :  "in", "size" :  1}                    , 

  "master_core_stat[4][phase_cdc40_rx]"                         : { "dir" :  "in", "size" :  3}                     , 
  "master_core_stat[4][phase_cdc40_tx]"                         : { "dir" :  "in", "size" : 10}                     , 
  "master_core_stat[4][rx_fec_corrected_latched]"               : { "dir" :  "in", "size" :  1}                     ,  
  "master_core_stat[4][rx_frame_locked]"                        : { "dir" :  "in", "size" :  1}                     ,        
  "master_core_stat[4][mgt_txpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[4][mgt_rxpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[4][mgt_buffbypass_rx_done]"                 : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[4][mgt_buffbypass_rx_error]"                : { "dir" :  "in", "size" :  1}                     ,
  "master_core_stat[4][mgt_powergood]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[4][mgt_reset_tx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[4][mgt_reset_rx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[4][mgt_rxpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[4][mgt_txpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[4][mgt_tx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[4][mgt_rx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[4][mgt_rxprbserr]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[4][mgt_rxprbslocked]"                       : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[4][mgt_drprdy_latched]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[4][mgt_drpdo]"                              : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[4][mgt_hptd_tx_pi_phase]"                   : { "dir" :  "in", "size" :  7}                     , 
  "master_core_stat[4][mgt_hptd_tx_fifo_fill_pd]"               : { "dir" :  "in", "size" : 32}                     , 
  "master_core_stat[4][mgt_hptd_ps_done_latched]"               : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[4][mgt_rxeq_dmonitor]"                      : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[4][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[4][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[4][tx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[4][rx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[4][rx_data_not_idle]"                       : { "dir" :  "in", "size" : 1}                      ,
  
  "master_tclink_stat[4][tclink_phase_detector]"                : { "dir" :  "in", "size" : 32}                     ,
  "master_tclink_stat[4][tclink_error_controller]"              : { "dir" :  "in", "size" : 48}                     ,
  "master_tclink_stat[4][tclink_phase_acc]"                     : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[4][tclink_operation_error]"               : { "dir" :  "in", "size" :  1}                     ,
  "master_tclink_stat[4][tclink_debug_tester_data_read]"        : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[4][tclink_loop_closed]"                   : { "dir" :  "in", "size" : 1}                     ,
  
  
  "master_firefly_reset_b_5"                                    : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_firefly_modsel_b_5"                                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[4][mgt_reset_all]"                          : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[4][mgt_reset_tx_pll_and_datapath]"          : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[4][mgt_reset_tx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[4][mgt_reset_rx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_stat[4][channel_ready]"                          : { "dir" :  "in", "size" : 1}                      ,     
  "master_core_stat[4][channel_controller_state]"                      : { "dir" :  "in", "size" : 17}                     ,     
  "master_core_stat[4][channel_controller_running]"                    : { "dir" :  "in", "size" : 1}                     ,   
  "master_core_ctrl[4][channel_controller_reset]"                      : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[4][channel_controller_enable]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[4][channel_controller_gentle]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},

  "master_core_ctrl[4][phase_cdc40_rx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[4][phase_cdc40_rx_calib]"                   : { "dir" : "out", "size" :  3, "init" :        0x0}, 
  "master_core_ctrl[4][phase_cdc40_tx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[4][phase_cdc40_tx_calib]"                   : { "dir" : "out", "size" : 10, "init" :        0x0}, 
  "master_core_ctrl[4][rx_fec_corrected_clear]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},   
  "master_core_ctrl[4][mgt_txpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[4][mgt_rxpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[4][mgt_loopback]"                           : { "dir" : "out", "size" :  3, "init" :        0x0},
  "master_core_ctrl[4][mgt_txprbsforceerr]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[4][mgt_txprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[4][mgt_rxprbscntreset]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[4][mgt_rxprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[4][mgt_drpwe]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[4][mgt_drpen]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[4][mgt_drpaddr]"                            : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_core_ctrl[4][mgt_drpdi]"                              : { "dir" : "out", "size" : 16, "init" :        0x0},  
  "master_core_ctrl[4][mgt_hptd_tx_pi_phase_calib]"             : { "dir" : "out", "size" :  7, "init" :        0x0}, 
  "master_core_ctrl[4][mgt_hptd_tx_ui_align_calib]"             : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[4][mgt_hptd_ps_strobe]"                     : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[4][mgt_hptd_ps_inc_ndec]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[4][mgt_hptd_ps_phase_step]"                 : { "dir" : "out", "size" :  4, "init" :        0x0}, 
  "master_core_ctrl[4][mgt_rxeq_rxlpmgcovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[4][mgt_rxeq_rxlpmhfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[4][mgt_rxeq_rxlpmlfklovrden]"               : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[4][mgt_rxeq_rxlpmosovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[4][mgt_rxeq_rxlpmen]"                       : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[4][mgt_rxeq_rxdfelfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[4][mgt_rxeq_rxdfelpmreset]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[4][mgt_rxeq_rxdfeutovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[4][mgt_rxeq_rxdfevpovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[4][mgt_rxeq_rxdfeagcovrden]"                : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[4][mgt_rxeq_rxosovrden]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  
  "master_tclink_ctrl[4][tclink_close_loop]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[4][tclink_offset_error]"                  : { "dir" : "out", "size" : 48, "init" :        0x0},
  "master_tclink_ctrl[4][tclink_metastability_deglitch]"        : { "dir" : "out", "size" : 16, "init" :     0x0052},
  "master_tclink_ctrl[4][tclink_phase_detector_navg]"           : { "dir" : "out", "size" : 12, "init" :      0x040},
  "master_tclink_ctrl[4][tclink_modulo_carrier_period]"         : { "dir" : "out", "size" : 48, "init" : 0x00007ff48348},
  "master_tclink_ctrl[4][tclink_Aie]"                           : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_tclink_ctrl[4][tclink_Aie_enable]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[4][tclink_Ape]"                           : { "dir" : "out", "size" :  4, "init" :        0xe},
  "master_tclink_ctrl[4][tclink_sigma_delta_clk_div]"           : { "dir" : "out", "size" : 16, "init" :     0x0197},
  "master_tclink_ctrl[4][tclink_enable_mirror]"                 : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_tclink_ctrl[4][tclink_Adco]"                          : { "dir" : "out", "size" : 48, "init" : 0x0000000ffe90},
  "master_tclink_ctrl[4][tclink_debug_tester_enable_stimulis]"  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[4][tclink_debug_tester_fcw]"              : { "dir" : "out", "size" : 10, "init" :      0x002},
  "master_tclink_ctrl[4][tclink_debug_tester_nco_scale]"        : { "dir" : "out", "size" :  5, "init" :       0x14},
  "master_tclink_ctrl[4][tclink_debug_tester_enable_stock_out]" : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[4][tclink_debug_tester_addr_read]"        : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_tclink_ctrl[4][tclink_master_rx_ui_period]"           : { "dir" : "out", "size" : 48, "init" : 0x000003ffa41a},
  
  # Master 5  
  "master_clk_offset_locked_6"                                  : { "dir" :  "in", "size" :  1}                     ,  
  "prbschk_master_locked_sync_6"                                : { "dir" :  "in", "size" :  1}                     ,    
  "master_firefly_modprs_b_sync_6"                              : { "dir" :  "in", "size" :  1}                     , 
  "master_firefly_int_b_sync_6"                                  : { "dir" :  "in", "size" :  1}                    , 

  "master_core_stat[5][phase_cdc40_rx]"                         : { "dir" :  "in", "size" :  3}                     , 
  "master_core_stat[5][phase_cdc40_tx]"                         : { "dir" :  "in", "size" : 10}                     , 
  "master_core_stat[5][rx_fec_corrected_latched]"               : { "dir" :  "in", "size" :  1}                     ,  
  "master_core_stat[5][rx_frame_locked]"                        : { "dir" :  "in", "size" :  1}                     ,        
  "master_core_stat[5][mgt_txpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[5][mgt_rxpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[5][mgt_buffbypass_rx_done]"                 : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[5][mgt_buffbypass_rx_error]"                : { "dir" :  "in", "size" :  1}                     ,
  "master_core_stat[5][mgt_powergood]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[5][mgt_reset_tx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[5][mgt_reset_rx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[5][mgt_rxpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[5][mgt_txpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[5][mgt_tx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[5][mgt_rx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[5][mgt_rxprbserr]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[5][mgt_rxprbslocked]"                       : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[5][mgt_drprdy_latched]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[5][mgt_drpdo]"                              : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[5][mgt_hptd_tx_pi_phase]"                   : { "dir" :  "in", "size" :  7}                     , 
  "master_core_stat[5][mgt_hptd_tx_fifo_fill_pd]"               : { "dir" :  "in", "size" : 32}                     , 
  "master_core_stat[5][mgt_hptd_ps_done_latched]"               : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[5][mgt_rxeq_dmonitor]"                      : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[5][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[5][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[5][tx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[5][rx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[5][rx_data_not_idle]"                       : { "dir" :  "in", "size" : 1}                      ,
  
  "master_tclink_stat[5][tclink_phase_detector]"                : { "dir" :  "in", "size" : 32}                     ,
  "master_tclink_stat[5][tclink_error_controller]"              : { "dir" :  "in", "size" : 48}                     ,
  "master_tclink_stat[5][tclink_phase_acc]"                     : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[5][tclink_operation_error]"               : { "dir" :  "in", "size" :  1}                     ,
  "master_tclink_stat[5][tclink_debug_tester_data_read]"        : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[5][tclink_loop_closed]"                   : { "dir" :  "in", "size" : 1}                     ,
  
  "master_firefly_reset_b_6"                                    : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_firefly_modsel_b_6"                                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[5][mgt_reset_all]"                          : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[5][mgt_reset_tx_pll_and_datapath]"          : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[5][mgt_reset_tx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[5][mgt_reset_rx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_stat[5][channel_ready]"                          : { "dir" :  "in", "size" : 1}                      ,     
  "master_core_stat[5][channel_controller_state]"                      : { "dir" :  "in", "size" : 17}                     ,     
  "master_core_stat[5][channel_controller_running]"                    : { "dir" :  "in", "size" : 1}                     ,   
  "master_core_ctrl[5][channel_controller_reset]"                      : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[5][channel_controller_enable]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[5][channel_controller_gentle]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},

  "master_core_ctrl[5][phase_cdc40_rx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[5][phase_cdc40_rx_calib]"                   : { "dir" : "out", "size" :  3, "init" :        0x0}, 
  "master_core_ctrl[5][phase_cdc40_tx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[5][phase_cdc40_tx_calib]"                   : { "dir" : "out", "size" : 10, "init" :        0x0}, 
  "master_core_ctrl[5][rx_fec_corrected_clear]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},   
  "master_core_ctrl[5][mgt_txpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[5][mgt_rxpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[5][mgt_loopback]"                           : { "dir" : "out", "size" :  3, "init" :        0x0},
  "master_core_ctrl[5][mgt_txprbsforceerr]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[5][mgt_txprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[5][mgt_rxprbscntreset]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[5][mgt_rxprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[5][mgt_drpwe]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[5][mgt_drpen]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[5][mgt_drpaddr]"                            : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_core_ctrl[5][mgt_drpdi]"                              : { "dir" : "out", "size" : 16, "init" :        0x0},  
  "master_core_ctrl[5][mgt_hptd_tx_pi_phase_calib]"             : { "dir" : "out", "size" :  7, "init" :        0x0}, 
  "master_core_ctrl[5][mgt_hptd_tx_ui_align_calib]"             : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[5][mgt_hptd_ps_strobe]"                     : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[5][mgt_hptd_ps_inc_ndec]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[5][mgt_hptd_ps_phase_step]"                 : { "dir" : "out", "size" :  4, "init" :        0x0}, 
  "master_core_ctrl[5][mgt_rxeq_rxlpmgcovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[5][mgt_rxeq_rxlpmhfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[5][mgt_rxeq_rxlpmlfklovrden]"               : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[5][mgt_rxeq_rxlpmosovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[5][mgt_rxeq_rxlpmen]"                       : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[5][mgt_rxeq_rxdfelfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[5][mgt_rxeq_rxdfelpmreset]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[5][mgt_rxeq_rxdfeutovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[5][mgt_rxeq_rxdfevpovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[5][mgt_rxeq_rxdfeagcovrden]"                : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[5][mgt_rxeq_rxosovrden]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  
  "master_tclink_ctrl[5][tclink_close_loop]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[5][tclink_offset_error]"                  : { "dir" : "out", "size" : 48, "init" :        0x0},
  "master_tclink_ctrl[5][tclink_metastability_deglitch]"        : { "dir" : "out", "size" : 16, "init" :     0x0052},
  "master_tclink_ctrl[5][tclink_phase_detector_navg]"           : { "dir" : "out", "size" : 12, "init" :      0x040},
  "master_tclink_ctrl[5][tclink_modulo_carrier_period]"         : { "dir" : "out", "size" : 48, "init" : 0x00007ff48348},
  "master_tclink_ctrl[5][tclink_Aie]"                           : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_tclink_ctrl[5][tclink_Aie_enable]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[5][tclink_Ape]"                           : { "dir" : "out", "size" :  4, "init" :        0xe},
  "master_tclink_ctrl[5][tclink_sigma_delta_clk_div]"           : { "dir" : "out", "size" : 16, "init" :     0x0197},
  "master_tclink_ctrl[5][tclink_enable_mirror]"                 : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_tclink_ctrl[5][tclink_Adco]"                          : { "dir" : "out", "size" : 48, "init" : 0x0000000ffe90},
  "master_tclink_ctrl[5][tclink_debug_tester_enable_stimulis]"  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[5][tclink_debug_tester_fcw]"              : { "dir" : "out", "size" : 10, "init" :      0x002},
  "master_tclink_ctrl[5][tclink_debug_tester_nco_scale]"        : { "dir" : "out", "size" :  5, "init" :       0x14},
  "master_tclink_ctrl[5][tclink_debug_tester_enable_stock_out]" : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[5][tclink_debug_tester_addr_read]"        : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_tclink_ctrl[5][tclink_master_rx_ui_period]"           : { "dir" : "out", "size" : 48, "init" : 0x000003ffa41a},
  
  # Master 6 
  "master_clk_offset_locked_7"                                  : { "dir" :  "in", "size" :  1}                     ,  
  "prbschk_master_locked_sync_7"                                : { "dir" :  "in", "size" :  1}                     ,    
  "master_firefly_modprs_b_sync_7"                              : { "dir" :  "in", "size" :  1}                     , 
  "master_firefly_int_b_sync_7"                                  : { "dir" :  "in", "size" :  1}                    , 

  "master_core_stat[6][phase_cdc40_rx]"                         : { "dir" :  "in", "size" :  3}                     , 
  "master_core_stat[6][phase_cdc40_tx]"                         : { "dir" :  "in", "size" : 10}                     , 
  "master_core_stat[6][rx_fec_corrected_latched]"               : { "dir" :  "in", "size" :  1}                     ,  
  "master_core_stat[6][rx_frame_locked]"                        : { "dir" :  "in", "size" :  1}                     ,        
  "master_core_stat[6][mgt_txpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[6][mgt_rxpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[6][mgt_buffbypass_rx_done]"                 : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[6][mgt_buffbypass_rx_error]"                : { "dir" :  "in", "size" :  1}                     ,
  "master_core_stat[6][mgt_powergood]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[6][mgt_reset_tx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[6][mgt_reset_rx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[6][mgt_rxpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[6][mgt_txpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[6][mgt_tx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[6][mgt_rx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[6][mgt_rxprbserr]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[6][mgt_rxprbslocked]"                       : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[6][mgt_drprdy_latched]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[6][mgt_drpdo]"                              : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[6][mgt_hptd_tx_pi_phase]"                   : { "dir" :  "in", "size" :  7}                     , 
  "master_core_stat[6][mgt_hptd_tx_fifo_fill_pd]"               : { "dir" :  "in", "size" : 32}                     , 
  "master_core_stat[6][mgt_hptd_ps_done_latched]"               : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[6][mgt_rxeq_dmonitor]"                      : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[6][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[6][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[6][tx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[6][rx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[6][rx_data_not_idle]"                       : { "dir" :  "in", "size" : 1}                      ,
  
  "master_tclink_stat[6][tclink_phase_detector]"                : { "dir" :  "in", "size" : 32}                     ,
  "master_tclink_stat[6][tclink_error_controller]"              : { "dir" :  "in", "size" : 48}                     ,
  "master_tclink_stat[6][tclink_phase_acc]"                     : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[6][tclink_operation_error]"               : { "dir" :  "in", "size" :  1}                     ,
  "master_tclink_stat[6][tclink_debug_tester_data_read]"        : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[6][tclink_loop_closed]"                   : { "dir" :  "in", "size" : 1}                     ,
  
  "master_firefly_reset_b_7"                                    : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_firefly_modsel_b_7"                                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[6][mgt_reset_all]"                          : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[6][mgt_reset_tx_pll_and_datapath]"          : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[6][mgt_reset_tx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[6][mgt_reset_rx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_stat[6][channel_ready]"                          : { "dir" :  "in", "size" : 1}                      ,     
  "master_core_stat[6][channel_controller_state]"                      : { "dir" :  "in", "size" : 17}                     ,     
  "master_core_stat[6][channel_controller_running]"                    : { "dir" :  "in", "size" : 1}                     ,   
  "master_core_ctrl[6][channel_controller_reset]"                      : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[6][channel_controller_enable]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[6][channel_controller_gentle]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},

  "master_core_ctrl[6][phase_cdc40_rx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[6][phase_cdc40_rx_calib]"                   : { "dir" : "out", "size" :  3, "init" :        0x0}, 
  "master_core_ctrl[6][phase_cdc40_tx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[6][phase_cdc40_tx_calib]"                   : { "dir" : "out", "size" : 10, "init" :        0x0}, 
  "master_core_ctrl[6][rx_fec_corrected_clear]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},   
  "master_core_ctrl[6][mgt_txpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[6][mgt_rxpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[6][mgt_loopback]"                           : { "dir" : "out", "size" :  3, "init" :        0x0},
  "master_core_ctrl[6][mgt_txprbsforceerr]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[6][mgt_txprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[6][mgt_rxprbscntreset]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[6][mgt_rxprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[6][mgt_drpwe]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[6][mgt_drpen]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[6][mgt_drpaddr]"                            : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_core_ctrl[6][mgt_drpdi]"                              : { "dir" : "out", "size" : 16, "init" :        0x0},  
  "master_core_ctrl[6][mgt_hptd_tx_pi_phase_calib]"             : { "dir" : "out", "size" :  7, "init" :        0x0}, 
  "master_core_ctrl[6][mgt_hptd_tx_ui_align_calib]"             : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[6][mgt_hptd_ps_strobe]"                     : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[6][mgt_hptd_ps_inc_ndec]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[6][mgt_hptd_ps_phase_step]"                 : { "dir" : "out", "size" :  4, "init" :        0x0}, 
  "master_core_ctrl[6][mgt_rxeq_rxlpmgcovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[6][mgt_rxeq_rxlpmhfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[6][mgt_rxeq_rxlpmlfklovrden]"               : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[6][mgt_rxeq_rxlpmosovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[6][mgt_rxeq_rxlpmen]"                       : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[6][mgt_rxeq_rxdfelfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[6][mgt_rxeq_rxdfelpmreset]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[6][mgt_rxeq_rxdfeutovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[6][mgt_rxeq_rxdfevpovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[6][mgt_rxeq_rxdfeagcovrden]"                : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[6][mgt_rxeq_rxosovrden]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  
  "master_tclink_ctrl[6][tclink_close_loop]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[6][tclink_offset_error]"                  : { "dir" : "out", "size" : 48, "init" :        0x0},
  "master_tclink_ctrl[6][tclink_metastability_deglitch]"        : { "dir" : "out", "size" : 16, "init" :     0x0052},
  "master_tclink_ctrl[6][tclink_phase_detector_navg]"           : { "dir" : "out", "size" : 12, "init" :      0x040},
  "master_tclink_ctrl[6][tclink_modulo_carrier_period]"         : { "dir" : "out", "size" : 48, "init" : 0x00007ff48348},
  "master_tclink_ctrl[6][tclink_Aie]"                           : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_tclink_ctrl[6][tclink_Aie_enable]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[6][tclink_Ape]"                           : { "dir" : "out", "size" :  4, "init" :        0xe},
  "master_tclink_ctrl[6][tclink_sigma_delta_clk_div]"           : { "dir" : "out", "size" : 16, "init" :     0x0197},
  "master_tclink_ctrl[6][tclink_enable_mirror]"                 : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_tclink_ctrl[6][tclink_Adco]"                          : { "dir" : "out", "size" : 48, "init" : 0x0000000ffe90},
  "master_tclink_ctrl[6][tclink_debug_tester_enable_stimulis]"  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[6][tclink_debug_tester_fcw]"              : { "dir" : "out", "size" : 10, "init" :      0x002},
  "master_tclink_ctrl[6][tclink_debug_tester_nco_scale]"        : { "dir" : "out", "size" :  5, "init" :       0x14},
  "master_tclink_ctrl[6][tclink_debug_tester_enable_stock_out]" : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[6][tclink_debug_tester_addr_read]"        : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_tclink_ctrl[6][tclink_master_rx_ui_period]"           : { "dir" : "out", "size" : 48, "init" : 0x000003ffa41a},
  
  # Master 7  
  "master_clk_offset_locked"                                  : { "dir" :  "in", "size" :  1}                     ,  
  "prbschk_master_locked_sync"                                : { "dir" :  "in", "size" :  1}                     ,    
  "master_firefly_modprs_b_sync"                              : { "dir" :  "in", "size" :  1}                     , 
  "master_firefly_int_b_sync"                                  : { "dir" :  "in", "size" :  1}                    , 

  "master_core_stat[7][phase_cdc40_rx]"                         : { "dir" :  "in", "size" :  3}                     , 
  "master_core_stat[7][phase_cdc40_tx]"                         : { "dir" :  "in", "size" : 10}                     , 
  "master_core_stat[7][rx_fec_corrected_latched]"               : { "dir" :  "in", "size" :  1}                     ,  
  "master_core_stat[7][rx_frame_locked]"                        : { "dir" :  "in", "size" :  1}                     ,        
  "master_core_stat[7][mgt_txpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[7][mgt_rxpll_lock]"                         : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[7][mgt_buffbypass_rx_done]"                 : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[7][mgt_buffbypass_rx_error]"                : { "dir" :  "in", "size" :  1}                     ,
  "master_core_stat[7][mgt_powergood]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[7][mgt_reset_tx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[7][mgt_reset_rx_done]"                      : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[7][mgt_rxpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[7][mgt_txpmaresetdone]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[7][mgt_tx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[7][mgt_rx_ready]"                           : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[7][mgt_rxprbserr]"                          : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[7][mgt_rxprbslocked]"                       : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[7][mgt_drprdy_latched]"                     : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[7][mgt_drpdo]"                              : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[7][mgt_hptd_tx_pi_phase]"                   : { "dir" :  "in", "size" :  7}                     , 
  "master_core_stat[7][mgt_hptd_tx_fifo_fill_pd]"               : { "dir" :  "in", "size" : 32}                     , 
  "master_core_stat[7][mgt_hptd_ps_done_latched]"               : { "dir" :  "in", "size" :  1}                     , 
  "master_core_stat[7][mgt_rxeq_dmonitor]"                      : { "dir" :  "in", "size" : 16}                     , 
  "master_core_stat[7][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[7][cdc_40_tx_ready]"                        : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[7][tx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[7][rx_user_data_ready]"                     : { "dir" :  "in", "size" : 1}                      ,
  "master_core_stat[7][rx_data_not_idle]"                       : { "dir" :  "in", "size" : 1}                      ,
  
  "master_tclink_stat[7][tclink_phase_detector]"                : { "dir" :  "in", "size" : 32}                     ,
  "master_tclink_stat[7][tclink_error_controller]"              : { "dir" :  "in", "size" : 48}                     ,
  "master_tclink_stat[7][tclink_phase_acc]"                     : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[7][tclink_operation_error]"               : { "dir" :  "in", "size" :  1}                     ,
  "master_tclink_stat[7][tclink_debug_tester_data_read]"        : { "dir" :  "in", "size" : 16}                     ,
  "master_tclink_stat[7][tclink_loop_closed]"                   : { "dir" :  "in", "size" : 1}                     ,
  
  "master_firefly_reset_b"                                    : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_firefly_modsel_b"                                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[7][mgt_reset_all]"                          : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[7][mgt_reset_tx_pll_and_datapath]"          : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[7][mgt_reset_tx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[7][mgt_reset_rx_datapath]"                  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_stat[7][channel_ready]"                          : { "dir" :  "in", "size" : 1}                      ,     
  "master_core_stat[7][channel_controller_state]"                      : { "dir" :  "in", "size" : 17}                     ,     
  "master_core_stat[7][channel_controller_running]"                    : { "dir" :  "in", "size" : 1}                     ,   
  "master_core_ctrl[7][channel_controller_reset]"                      : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[7][channel_controller_enable]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[7][channel_controller_gentle]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},

  "master_core_ctrl[7][phase_cdc40_rx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[7][phase_cdc40_rx_calib]"                   : { "dir" : "out", "size" :  3, "init" :        0x0}, 
  "master_core_ctrl[7][phase_cdc40_tx_force]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[7][phase_cdc40_tx_calib]"                   : { "dir" : "out", "size" : 10, "init" :        0x0}, 
  "master_core_ctrl[7][rx_fec_corrected_clear]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},   
  "master_core_ctrl[7][mgt_txpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[7][mgt_rxpolarity]"                         : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[7][mgt_loopback]"                           : { "dir" : "out", "size" :  3, "init" :        0x0},
  "master_core_ctrl[7][mgt_txprbsforceerr]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[7][mgt_txprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[7][mgt_rxprbscntreset]"                     : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[7][mgt_rxprbssel]"                          : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_core_ctrl[7][mgt_drpwe]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[7][mgt_drpen]"                              : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[7][mgt_drpaddr]"                            : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_core_ctrl[7][mgt_drpdi]"                              : { "dir" : "out", "size" : 16, "init" :        0x0},  
  "master_core_ctrl[7][mgt_hptd_tx_pi_phase_calib]"             : { "dir" : "out", "size" :  7, "init" :        0x0}, 
  "master_core_ctrl[7][mgt_hptd_tx_ui_align_calib]"             : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[7][mgt_hptd_ps_strobe]"                     : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[7][mgt_hptd_ps_inc_ndec]"                   : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[7][mgt_hptd_ps_phase_step]"                 : { "dir" : "out", "size" :  4, "init" :        0x0}, 
  "master_core_ctrl[7][mgt_rxeq_rxlpmgcovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[7][mgt_rxeq_rxlpmhfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[7][mgt_rxeq_rxlpmlfklovrden]"               : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[7][mgt_rxeq_rxlpmosovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0}, 
  "master_core_ctrl[7][mgt_rxeq_rxlpmen]"                       : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_core_ctrl[7][mgt_rxeq_rxdfelfovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[7][mgt_rxeq_rxdfelpmreset]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[7][mgt_rxeq_rxdfeutovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[7][mgt_rxeq_rxdfevpovrden]"                 : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[7][mgt_rxeq_rxdfeagcovrden]"                : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_core_ctrl[7][mgt_rxeq_rxosovrden]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  
  "master_tclink_ctrl[7][tclink_close_loop]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[7][tclink_offset_error]"                  : { "dir" : "out", "size" : 48, "init" :        0x0},
  "master_tclink_ctrl[7][tclink_metastability_deglitch]"        : { "dir" : "out", "size" : 16, "init" :     0x0052},
  "master_tclink_ctrl[7][tclink_phase_detector_navg]"           : { "dir" : "out", "size" : 12, "init" :      0x040},
  "master_tclink_ctrl[7][tclink_modulo_carrier_period]"         : { "dir" : "out", "size" : 48, "init" : 0x00007ff48348},
  "master_tclink_ctrl[7][tclink_Aie]"                           : { "dir" : "out", "size" :  4, "init" :        0x0},
  "master_tclink_ctrl[7][tclink_Aie_enable]"                    : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[7][tclink_Ape]"                           : { "dir" : "out", "size" :  4, "init" :        0xe},
  "master_tclink_ctrl[7][tclink_sigma_delta_clk_div]"           : { "dir" : "out", "size" : 16, "init" :     0x0197},
  "master_tclink_ctrl[7][tclink_enable_mirror]"                 : { "dir" : "out", "size" :  1, "init" :        0x1},
  "master_tclink_ctrl[7][tclink_Adco]"                          : { "dir" : "out", "size" : 48, "init" : 0x0000000ffe90},
  "master_tclink_ctrl[7][tclink_debug_tester_enable_stimulis]"  : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[7][tclink_debug_tester_fcw]"              : { "dir" : "out", "size" : 10, "init" :      0x002},
  "master_tclink_ctrl[7][tclink_debug_tester_nco_scale]"        : { "dir" : "out", "size" :  5, "init" :       0x14},
  "master_tclink_ctrl[7][tclink_debug_tester_enable_stock_out]" : { "dir" : "out", "size" :  1, "init" :        0x0},
  "master_tclink_ctrl[7][tclink_debug_tester_addr_read]"        : { "dir" : "out", "size" : 10, "init" :        0x0},
  "master_tclink_ctrl[7][tclink_master_rx_ui_period]"           : { "dir" : "out", "size" : 48, "init" : 0x000003ffa41a}
}
