AXI_CONTROL_SETS:
  AXI_MASTER_CTRL:
    axi_interconnect: "${::AXI_INTERCONNECT_NAME}"
    axi_clk: "${::AXI_MASTER_CLK}"
    axi_rstn: "${::AXI_PRIMARY_MASTER_RSTN}"
    axi_freq: "${::AXI_MASTER_CLK_FREQ}"
  AXI_C2C_CTRL:
    axi_interconnect: "${::AXI_C2C_INTERCONNECT_NAME}"
    axi_clk: "${::AXI_MASTER_CLK}"
    axi_rstn: "${::AXI_C2C_MASTER_RSTN}"
    axi_freq: "${::AXI_MASTER_CLK_FREQ}"
  AXI_LOCAL_CTRL:
    axi_interconnect: "AXI_LOCAL_CTRL"
    axi_clk: "${::AXI_MASTER_CLK}"
    axi_rstn: "${::AXI_PRIMARY_SLAVE_RSTN}"
    axi_freq: "${::AXI_MASTER_CLK_FREQ}"

AXI_SLAVES:

  ADD_PL_MASTER:
    TCL_CALL:
      command: "AXI_PL_MASTER_PORT"
      name: AXIM_PL
      axi_clk: AXI_CLK_PL
      axi_rstn: AXI_RSTN_PL
      axi_freq: 50     
    SUB_SLAVES:
      AXI_LOCAL_CTRL:
        TCL_CALL:
          command: "BUILD_CHILD_AXI_INTERCONNECT"
          axi_clk: "${::AXI_MASTER_CLK}"
          axi_rstn: "${::AXI_PRIMARY_SLAVE_RSTN}"
          parent: "AXIM_PL ${::AXI_INTERCONNECT_NAME}"
          master_clk: "AXI_CLK_PL ${::AXI_MASTER_CLK}"
          master_rstn: "AXI_RSTN_PL ${::AXI_PRIMARY_SLAVE_RSTN}"
        SUB_SLAVES:      
          PL_MEM:
            TCL_CALL:
              command: "AXI_IP_BRAM"
              axi_control: "${::AXI_LOCAL_CTRL}"
              addr:
                offset: -1
                range: "8K"
            XML: "address_table/modules/PL_MEM.xml"
            UHAL_BASE: 0x15000000
          SERV:
            TCL_CALL:
              command: "AXI_PL_DEV_CONNECT"
              axi_control: "${::AXI_LOCAL_CTRL}"
            XML: "address_table/modules/SERV_rev1.xml"
            UHAL_BASE: 0x04000000
            HDL:
              map_template: "axi_generic/template_map.vhd"
          SLAVE_I2C:
            TCL_CALL:
              command: "AXI_PL_DEV_CONNECT"
              axi_control: "${::AXI_LOCAL_CTRL}"
              addr:
                offset: -1
                range: "8K"
            XML: "address_table/modules/SLAVE_I2C.xml"
            UHAL_BASE: 0x05000000


  INT_AXI_FW:
    TCL_CALL:
      command: "AXI_IP_AXI_FW"
      axi_fw_bus: "/${::ZYNQ_NAME}/M_AXI_GP0"
      axi_control: "${::AXI_C2C_CTRL}"
    XML: "address_table/modules/INT_AXI_FW.xml"
    UHAL_BASE: 0x20000000

  PLXVC:
    TCL_CALL:
      command: "AXI_PL_DEV_CONNECT"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0x40010000"
        range: "64K"
    XML: "address_table/modules/plXVC_rev1.xml"
    UHAL_BASE: 0x06000000
    HDL: 
      map_template: "axi_generic/template_map.vhd"


  CM:
    TCL_CALL:
      command: "AXI_PL_DEV_CONNECT"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0x40100000"
        range: "128K"
    XML: "address_table/modules/CM_7s.xml"
    UHAL_BASE: 0x03000000
    HDL: 
      map_template: "axi_generic/template_map_withbram.vhd"

  SM_INFO:
    TCL_CALL:
      command: "AXI_PL_DEV_CONNECT"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0x4000C000"
        range: "8K"
    XML: "address_table/modules/FW_INFO.xml"
    UHAL_BASE: 0x0A000000
    HDL: 
      map_template: "axi_generic/template_map.vhd"

  MONITOR:
    TCL_CALL:
      command: "AXI_IP_XADC"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0x40040000"
        range: "64K"
    XML: "address_table/modules/MONITOR.xml"
    UHAL_BASE: 0x0B000000

  CM1_UART:
    TCL_CALL:
      command: "AXI_IP_UART"
      baud_rate: "115200"
      irq_port: "${::IRQ0_INTR_CTRL}"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0x40140000"
        range: "8K"
      dt_data: "port-number = <1>;"

  CM2_UART:
    TCL_CALL:
      command: "AXI_IP_UART"
      baud_rate: "115200"
      irq_port: "${::IRQ0_INTR_CTRL}"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0x40150000"
        range: "8K"
      dt_data: "port-number = <2>;"

  ESM_UART:
    TCL_CALL:
      command: "AXI_IP_UART"
      baud_rate: "115200"
      irq_port: "${::IRQ0_INTR_CTRL}"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0x40160000"
        range: "8K"
      dt_data: "port-number = <3>;"


  SI:
    TCL_CALL:
      command: "AXI_IP_I2C"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0x41600000"
        range: "8K"
      irq_port: "${::IRQ0_INTR_CTRL}"
      dt_data: "compatible = \"xlnx,axi-iic-2.0\", \"xlnx,xps-iic-2.00.a\";"



  IRQ_CTRL:
    XML: "address_table/modules/INTERRUPT_CONTROLLER.xml"
    UHAL_BASE: 0x16000000


CORES:
  onboardclk:
    TCL_CALL:
      command: BuildClockWizard
      in_clk_type: Differential_clock_capable_pin
      in_clk_freq_MHZ: 200
      out_clks:
        1: 200
        2: 50




