#!/bin/sh

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

# Must be a valid filename
NAME=sm_boot
PIDFILE=/var/run/$NAME.pid
#This is the command to be run, give the full pathname
DAEMON_NAME=SM_boot
DAEMON=/tmp/bin/$DAEMON_NAME
DAEMON_OPTS=""

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
	#copy new file over if needed
	if [ ! -f /work/bin/$DAEMON_NAME ]; then 
	   cp -u /work/bin/$DAEMON_NAME $DAEMON
	fi 
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        echo "."
	;;
  stop)
        echo -n "Stopping daemon: "$NAME
	start-stop-daemon --stop --signal INT --quiet --oknodo --pidfile $PIDFILE
        echo "."
	;;
  restart)
        echo -n "Restarting daemon: "$NAME

	start-stop-daemon --stop --signal INT --quiet --oknodo --retry 30 --pidfile $PIDFILE
	#copy new file over if needed
	if [ ! -f /work/bin/$DAEMON_NAME ]; then 
	   cp -u /work/bin/$DAEMON_NAME $DAEMON
	fi 

	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
	echo "."
	;;

  *)
  echo "Usage: "$1" {start|stop|restart}"
  exit 1
esac

exit 0
