AXI_SLAVES:
  PL_MEM:
    TCL_CALL:
      command: "AXI_IP_BRAM"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xA0000000"
        range: "8K"
    XML:
      - "address_table/modules/PL_MEM.xml"
      - "address_table/modules/I2C_REGULATOR_MONITOR.xml"
    UHAL_BASE: 0x15000000

  SI:
    TCL_CALL:
      command: "AXI_IP_I2C"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xA1600000"
        range: "8K"

  SERV:
    TCL_CALL:
      command: "AXI_PL_DEV_CONNECT"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xA3C20000"
        range: "8K"
    XML:
      - "address_table/modules/SERV_rev2.xml"
    UHAL_BASE: 0x04000000
    HDL: "src/services"

  PLXVC:
    TCL_CALL:
      command: "AXI_PL_DEV_CONNECT"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xA0010000"
        range: "64K"
    XML:
      - "address_table/modules/plXVC_rev2.xml"
      - "address_table/modules/plXVC_single.xml"
    UHAL_BASE: 0x06000000
    HDL: "src/plXVC"


  SLAVE_I2C:
    TCL_CALL:
      command: "AXI_PL_DEV_CONNECT"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xA0008000"
        range: "8K"
    XML:
      - "address_table/modules/SLAVE_I2C.xml"
    UHAL_BASE: 0x05000000

  SM_INFO:
    TCL_CALL:
      command: "AXI_PL_DEV_CONNECT"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xA000C000"
        range: "8K"
    XML:
      - "address_table/modules/FW_INFO.xml"
    UHAL_BASE: 0x0A000000
    HDL: "src/SM_info"

  MONITOR:
    TCL_CALL:
      command: "AXI_IP_SYS_MGMT"
      axi_control: "${::AXI_MASTER_CTRL}"
      enable_i2c_pins: 0
      addr:
        offset: "0xA0040000"
        range: "64K"
    XML:
      - "address_table/modules/MONITOR_USP.xml"
    UHAL_BASE: 0x0B000000


  ESM_UART:
    TCL_CALL:
      command: "AXI_IP_UART"
      baud_rate: "115200"
      irq_port: "${::IRQ_ORR}/in2"
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xA0160000"
        range: "8K"

